apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: abdulrehmanconq/shop
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: shoping
            - name: MONGO_URI
              value: "mongodb://shop-mongo-service:27017/shop"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: shop
  ports:
    - name: shop
      protocol: TCP
      targetPort: 3000
      port: 3000
